### ISSUE TITLE
IndexOutOfBoundsException when choosing a date

### ISSUE THREAD

**Issue by idon14** [Applandeo/Material-Calendar-View#130]
I have a CalendarView, in which I disabled a few dates, and set minimum and maximum dates for it.
When I press on an enabled date, the app crashes and I see the following error log:

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.app, PID: 19945
                  java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                      at java.util.ArrayList.get(ArrayList.java:437)
                      at com.applandeo.materialcalendarview.adapters.CalendarPageAdapter.getSelectedDay(CalendarPageAdapter.java:88)
                      at com.applandeo.materialcalendarview.listeners.DayRowClickListener.selectOneDay(DayRowClickListener.java:70)
                      at com.applandeo.materialcalendarview.listeners.DayRowClickListener.onItemClick(DayRowClickListener.java:53)
                      at android.widget.AdapterView.performItemClick(AdapterView.java:318)
                      at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
                      at android.widget.AbsListView$3.run(AbsListView.java:4052)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

I have seen something about that it has to do something with the Glide library, which I'm using.

**Comment by tarekmabdallah91** [comment]
I faced this issue too when clicked on a day in any month other than the current one ! 
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.applandeo.materialcalendarview.adapters.CalendarPageAdapter.getSelectedDay(CalendarPageAdapter.java:88)
        at com.applandeo.materialcalendarview.listeners.DayRowClickListener.selectOneDay(DayRowClickListener.java:70)
        at com.applandeo.materialcalendarview.listeners.DayRowClickListener.onItemClick(DayRowClickListener.java:53)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1202)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3189)
        at android.widget.AbsListView$3.run(AbsListView.java:4243)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6316)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```
my code ... try and catch doesn't work here !
```
calendarView.setDisabledDays(getOffDays());
        invalidateRecursive(calendarView);
            calendarView.setOnDayClickListener(eventDay -> {
                Calendar clickedDayCalendar = eventDay.getCalendar();
               try {
                      ......
                   } catch (IndexOutOfBoundsException ignored) {
                  }
            });
```

**Comment by asknask** [comment]
How is this issue resolved?
