### ISSUE TITLE
Fatal Exception: android.view.InflateException

### ISSUE THREAD

**Issue by arutkayb** [Applandeo/Material-Calendar-View#211]
I see weird xml based errors on my Firebase crash analytics:

**Fatal Exception: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.applandeo.materialcalendarview.CalendarView**

**Caused by android.view.InflateException: Binary XML file line #18: Error inflating class com.applandeo.materialcalendarview.CalendarView
**

**Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800ab
       at android.content.res.ResourcesImpl.getResourceName + 255(ResourcesImpl.java:255)
       at android.content.res.ResourcesImpl.loadDrawableForCookie + 785(ResourcesImpl.java:785)
       at android.content.res.ResourcesImpl.loadDrawable + 631(ResourcesImpl.java:631)
       at android.content.res.Resources.loadDrawable + 897(Resources.java:897)
       at android.content.res.TypedArray.getDrawableForDensity + 955(TypedArray.java:955)
       at android.content.res.TypedArray.getDrawable + 930(TypedArray.java:930)
       at android.widget.ImageView.(ImageView.java:189)
       at android.widget.ImageButton.(ImageButton.java:86)
       at android.widget.ImageButton.(ImageButton.java:82)
       at androidx.appcompat.widget.AppCompatImageButton.(Unknown Source:4)
       at androidx.appcompat.widget.AppCompatImageButton.(Unknown Source:4)
       at androidx.appcompat.widget.AppCompatImageButton.(Unknown Source:4)
       at androidx.appcompat.widget.AppCompatImageButton.(Unknown Source:2)
       at androidx.appcompat.widget.AppCompatImageButton.(Unknown Source:2)
       at androidx.appcompat.widget.AppCompatImageButton.(Unknown Source:2)
       at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:2)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:214)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:214)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:140)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java)
       at android.view.LayoutInflater.createViewFromTag + 772(LayoutInflater.java:772)
       at android.view.LayoutInflater.createViewFromTag + 730(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate + 863(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate + 866(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate + 374(LayoutInflater.java:374)
       at com.applandeo.materialcalendarview.CalendarView.initControl(CalendarView.java:19)
       at com.applandeo.materialcalendarview.CalendarView.(Unknown Source:24)
       at com.applandeo.materialcalendarview.CalendarView.(Unknown Source:24)
       at com.applandeo.materialcalendarview.CalendarView.(Unknown Source:24)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance + 343(Constructor.java:343)
       at android.view.LayoutInflater.createView + 647(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag + 790(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag + 730(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate + 863(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate + 866(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate + 866(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at centertable.advancedscalendar.modules.calendar.CalendarFragment.onCreateView(CalendarFragment.java:6)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:20)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:590)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:590)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:38)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:46)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:46)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:165)
       at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManagerImpl.java:38)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:114)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:114)
       at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManagerImpl.java:88)
       at androidx.fragment.app.FragmentManagerImpl.removeFragment(FragmentManagerImpl.java:21)
       at androidx.fragment.app.FragmentManagerImpl.getFragments(FragmentManagerImpl.java:9)
       at androidx.fragment.app.FragmentManagerImpl.findFragmentUnder(FragmentManagerImpl.java:6)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:24)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:659)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:659)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:38)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:46)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:46)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:165)
       at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManagerImpl.java:38)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:114)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java:114)
       at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManagerImpl.java:88)
       at androidx.fragment.app.FragmentManagerImpl.removeFragment(FragmentManagerImpl.java:21)
       at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:25)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart + 1391(Instrumentation.java:1391)
       at android.app.Activity.performStart + 7165(Activity.java:7165)
       at android.app.ActivityThread.handleStartActivity + 2975(ActivityThread.java:2975)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence + 180(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath + 165(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState + 142(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute + 70(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage + 1816(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6718(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 858(ZygoteInit.java:858)**

**Comment by Afur** [comment]
@arutkayb From the stacktrace it looks that's issue related to resource that you wanted to use rather that with this library
