### ISSUE TITLE
IndexOutOfBoundsException when choosing a date

### ISSUE THREAD

**Issue by asknask** [Applandeo/Material-Calendar-View#219]
This issue was shared earlier but then closed by the OP. Issue occurs when `setDisabledDays` is used.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.homefiks, PID: 20664
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.applandeo.materialcalendarview.adapters.CalendarPageAdapter.getSelectedDay(CalendarPageAdapter.java:88)
        at com.applandeo.materialcalendarview.listeners.DayRowClickListener.selectOneDay(DayRowClickListener.java:70)
        at com.applandeo.materialcalendarview.listeners.DayRowClickListener.onItemClick(DayRowClickListener.java:53)
        at android.widget.AdapterView.performItemClick(AdapterView.java:362)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
        at android.widget.AbsListView$7.run(AbsListView.java:6612)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

**Comment by AngelDamyanov** [comment]
news to this?

**Comment by awaisyaseen59** [comment]
i'm still facing this issue.

**Comment by kedartendolkar** [comment]
I was facing same issue. Resolved it by removing the current date from disabled date.
For eg. If current date is 10th May 2020 and is added to disabled date then we will get the crash.
Hope it helps. :)
