### ISSUE TITLE
Inflate Exception When Adding XML to fragment

### ISSUE THREAD

**Issue by zoranSpare** [Applandeo/Material-Calendar-View#244]
Hi Guys,

I was using the view via the date picker dialog and all was working great. I had to move to the view based XML version but the app crashes on inflate with the following error:
`
android.view.InflateException: Binary XML file line #132 in com.sparecreative.equiptapp:layout/fragment_roster_date_picker: Binary XML file line #132 in com.sparecreative.equiptapp:layout/fragment_roster_date_picker: Error inflating class com.applandeo.materialcalendarview.CalendarView
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at com.applandeo.materialcalendarview.CalendarView.<init>(CalendarView.java:295)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at com.sparecreative.equiptapp.fragments.RosterDatePickerFragment.onCreateView(RosterDatePickerFragment.java:54) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
`
I'd really appreciate any advice.

**Comment by aruns2896** [comment]
Is it solved???

**Comment by zoranSpare** [comment]
In the end we went with another Calendar Widget which we could get to work.

**Comment by aruns2896** [comment]
@zoranSpare Which one?

**Comment by zoranSpare** [comment]
> @zoranSpare Which one?

https://github.com/savvisingh/DateRangePicker

**Comment by aruns2896** [comment]
@zoranSpare Okay thank you,  is there any other good library for events calendar based on Java??

**Comment by zoranSpare** [comment]
The one above suited our needs and was java. We made small tweaks for our specific purpose but overall it worked great.
