### ISSUE TITLE
Version 1.7.0 Fails on Sumsung Devices Fatal Exception: android.view.InflateException

### ISSUE THREAD

**Issue by samuelowino** [Applandeo/Material-Calendar-View#346]
Material Calendar View throws Fatal Exception: android.view.InflateException on particular Samsung devices but works fine all other devices.  Caught this error on :

Brand: samsung
Model: Galaxy A20s
Orientation: Portrait
RAM free: 1.52 GB
Disk free: 43.63 GB

Version: 10
Orientation: Portrait
Rooted: No

> This failure does not occur on a majority of other devices.

## Stacktrace

>Fatal Exception: android.view.InflateException: Binary XML file line #24 in org.myapp.com:layout/mylayout: Binary XML file line >#24 in org.myapp.com:layout/mylayout: Error inflating class com.applandeo.materialcalendarview.CalendarView

> Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:854)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at org.myapp.com.views.fragments.dashboard.CalendarFragment.onCreateView(CalendarFragment.java:68)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
       at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:246)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:26415)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
       at android.view.View.measure(View.java:26415)
       at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1010)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3609)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2352)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2644)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9003)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:729)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
   >    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

>Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0801b5
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:289)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:837)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:683)
       at android.content.res.Resources.loadDrawable(Resources.java:931)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1005)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
       at android.widget.ImageView.<init>(ImageView.java:207)
       at android.widget.ImageButton.<init>(ImageButton.java:96)
       at android.widget.ImageButton.<init>(ImageButton.java:92)
       at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:75)
       at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:70)
       at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:219)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:135)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
       at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
       at com.applandeo.materialcalendarview.CalendarView.initControl(CalendarView.java:103)
       at com.applandeo.materialcalendarview.CalendarView.<init>(CalendarView.java:74)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:854)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at org.myapp.com.views.fragments.dashboard.CalendarFragment.onCreateView(CalendarFragment.java:68)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
       at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:246)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:26415)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
       at android.view.View.measure(View.java:26415)
       at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1010)
       at android.view.View.measure(View.java:26415)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3609)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2352)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2644)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9003)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:729)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
>

**Comment by kormateusz** [comment]
Is this bug still present in v1.9.0-rc02?

**Comment by samuelowino** [comment]
I am yet to test on that version 😬.

**Comment by samuelowino** [comment]
> Is this bug still present in v1.9.0-rc02?

I can confirm that this bug is still present in 1.7.0

>Fatal Exception: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.applandeo.materialcalendarview.CalendarView

**Comment by kormateusz** [comment]
But what about v1.9.0-rc02?

**Comment by samuelowino** [comment]
> But what about v1.9.0-rc02?

v1.7 seems to be the last stable release. Can I use v1.9.0-rc02 in production

**Comment by Dashesh** [comment]
Does v1.6.0 have this issue? or just 1.7. I can use 1.6.0 in production till this gets fixed.

**Comment by samuelowino** [comment]
I gave up on this and just wrote up a custom calendar view specific to my project.
