### ISSUE TITLE
App Crashes if you try to clear selected days when no days selected

### ISSUE THREAD

**Issue by MaxSiominDev** [Applandeo/Material-Calendar-View#430]

**Comment by ThiagoLeao1987** [comment]
Hello guys, how are u?
I've a doubt, about accessibility.
does this lib support accessibility/talkback?
thank u!!

**Comment by openxcellpooja** [comment]
App crashed when try to select a date from the calender.
java.util.NoSuchElementException: List is empty.
               	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
               	at com.applandeo.materialcalendarview.adapters.CalendarPageAdapter.getSelectedDay(CalendarPageAdapter.kt:35)
               	at com.applandeo.materialcalendarview.listeners.DayRowClickListener.selectOneDay(DayRowClickListener.kt:60)
               	at com.applandeo.materialcalendarview.listeners.DayRowClickListener.onItemClick(DayRowClickListener.kt:52)
               	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
               	at android.widget.AbsListView.performItemClick(AbsListView.java:1273)
               	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3286)
               	at android.widget.AbsListView$3.run(AbsListView.java:4252)
               	at android.os.Handler.handleCallback(Handler.java:959)
               	at android.os.Handler.dispatchMessage(Handler.java:100)
               	at android.os.Looper.loopOnce(Looper.java:232)
               	at android.os.Looper.loop(Looper.java:317)

![Screenshot 2024-12-18 at 11 10 47 AM](https://github.com/user-attachments/assets/9f2c0712-ce70-4140-8ab8-0c8875114b7d)

Getting crash on this line
get() = calendarProperties.selectedDays.first()

Also attach the screen shot of the file where I redirected when clicking on the crash.
