### ISSUE TITLE
upgraded to version 1.4.0 with and without proguard I get the following error log

### ISSUE THREAD

**Issue by MbaiMburu** [Applandeo/Material-Calendar-View#81]
05-15 18:35:49.117 14839-14839/com.fobisoft.madarakaxpress E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fobisoft.madarakaxpress, PID: 14839
    java.lang.NoSuchMethodError: com.bumptech.glide.RequestBuilder.into
        at com.applandeo.materialcalendarview.utils.ImageUtils.loadResource(ImageUtils.java:27)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter.lambda$loadIcon$3(CalendarDayAdapter.java:127)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter$$Lambda$4.accept(Unknown Source)
        at com.annimon.stream.Optional.ifPresent(Optional.java:96)
        at com.annimon.stream.Optional.executeIfPresent(Optional.java:126)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter.loadIcon(CalendarDayAdapter.java:125)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter.getView(CalendarDayAdapter.java:65)
        at android.widget.AbsListView.obtainView(AbsListView.java:2338)
        at android.widget.GridView.makeAndAddView(GridView.java:1346)
        at android.widget.GridView.makeRow(GridView.java:345)
        at android.widget.GridView.fillDown(GridView.java:287)
        at android.widget.GridView.fillFromTop(GridView.java:422)
        at android.widget.GridView.layoutChildren(GridView.java:1234)
        at android.widget.AbsListView.onLayout(AbsListView.java:2149)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1877)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1653)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1606)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
        at android.view.View.layout(View.java:15142)
        at android.view.ViewGroup.layout(ViewGroup.java:4862)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2317)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
        at android.view.Choreographer.doCallbacks(Choreographer.java:591)
        at android.view.Choreographer.doFrame(Choreographer.java:560)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
    	at android.os.Han

**Comment by kormateusz** [comment]
Refer to: https://github.com/Applandeo/Material-Calendar-View/issues/82
