### ISSUE TITLE
With latest version of Glide not working app get crash

### ISSUE THREAD

**Issue by vandanabpatel** [Applandeo/Material-Calendar-View#82]
implementation 'com.github.bumptech.glide:glide:4.6.1'

**Comment by petitJAM** [comment]
I believe I have the same problem. I've added the stack trace below.

```
05-24 12:33:23.037 18576-18576/com.mypackage.android.athing E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mypackage.android.athing, PID: 18576
    java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.mypackage.android.athing-n7OoZyGI47qaflwAyuj3Lg==/split_lib_dependencies_apk.apk)
        at com.applandeo.materialcalendarview.utils.ImageUtils.loadResource(ImageUtils.java:27)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter.lambda$loadIcon$3(CalendarDayAdapter.java:127)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter$$Lambda$4.accept(Unknown Source:8)
        at com.annimon.stream.Optional.ifPresent(Optional.java:96)
        at com.annimon.stream.Optional.executeIfPresent(Optional.java:126)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter.loadIcon(CalendarDayAdapter.java:125)
        at com.applandeo.materialcalendarview.adapters.CalendarDayAdapter.getView(CalendarDayAdapter.java:65)
        at android.widget.AbsListView.obtainView(AbsListView.java:2365)
        at android.widget.GridView.makeAndAddView(GridView.java:1439)
        at android.widget.GridView.makeRow(GridView.java:366)
        at android.widget.GridView.fillDown(GridView.java:307)
        at android.widget.GridView.fillFromTop(GridView.java:442)
        at android.widget.GridView.layoutChildren(GridView.java:1283)
        at android.widget.AbsListView.onLayout(AbsListView.java:2164)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1606)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by kormateusz** [comment]
@petitJAM It's because we load images asynchronously. We will make more tests and probably remove it in one of next release if calendar will be working without any issues.
